service: newsletter-signup

provider:
  name: aws
  runtime: nodejs4.3
  profile: ${opt:profile}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  post:
    handler: src/users.post
    events:
      - http:
          path: users
          method: POST
          cors: true
          request:
            template:
              application/json: '{ "body": "$input.json(''$'')" }'
    memorySize: 128

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table 
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1